### ISSUE TITLE
M/R Not updating immediately

### ISSUE THREAD

**Issue by DNAcer** [404Wolf/NATuG#9]
For some reason, when I change the m value of some domain, I need to click on a few boxes before the M/R value updates.

**Comment by 404Wolf** [comment]
@DNAcer 
Currently it is set to update on a editingFinished event for the m input box. This means that when you click out of the box, or tab, or return, it emits the signal, and updates. Some potential solutions if you want instant updating:

- Use the valueChanged event. This would cause an update right away, but could be annoying, since as you enter a double digit m value it would update for each digit entry/removal.
- Add a valueChanged event with a timer. When the value is changed begin a timer, and at the end of .5 seconds use the current value for the update. This would mean that if they begin entering a double digit number it won't update until they've finished (unless they type slowly).
- Leave it as is and suggest users tab (which now works properly) to update.

What do you think?

**Comment by 404Wolf** [comment]
I'm sorry, I misunderstood the issue. I've gone ahead and fixed the bug.
